const homePage=document.getElementById("homePage"),browserPage=document.getElementById("browserPage"),address=document.getElementById("address"),webview=document.getElementById("webview"),blocked=document.getElementById("blocked"),pageTitle=document.getElementById("pageTitle"),tabsEl=document.getElementById("tabs"),menu=document.getElementById("menu"),historyPanel=document.getElementById("historyPanel"),historyList=document.getElementById("historyList");let tabs=[{id:1,url:"",title:"Tab baru"}],active=1,desktop=false;const key="webbrowser-history";let history=JSON.parse(localStorage.getItem(key)||"[]");
function activeTab(){return tabs.find(t=>t.id===active)} function save(){localStorage.setItem(key,JSON.stringify(history.slice(0,100)))} function renderTabs(){tabsEl.innerHTML=tabs.map(t=>'<div class="tab '+(t.id===active?"active":"")+'" data-id="'+t.id+'"><span class="tab-title">'+esc(t.title||"Tab baru")+'</span><button class="tab-close" data-close="'+t.id+'">×</button></div>').join("");tabsEl.querySelectorAll(".tab").forEach(e=>e.onclick=()=>{if(e.querySelector("[data-close]")?.matches(":hover"))return;active=+e.dataset.id;showTab()});tabsEl.querySelectorAll("[data-close]").forEach(e=>e.onclick=x=>{x.stopPropagation();closeTab(+e.dataset.close)})}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function showTab(){const t=activeTab();address.value=t.url||"";pageTitle.textContent=t.title||"Halaman";renderTabs();if(t.url){homePage.classList.add("hidden");browserPage.classList.remove("hidden");webview.src=t.url}else{browserPage.classList.add("hidden");homePage.classList.remove("hidden")}}
function normalize(v){v=v.trim();if(!v)return"";if(/^https?:\/\//i.test(v))return v;if(v.includes(".")&&!v.includes(" "))return"https://"+v;return"https://www.google.com/search?q="+encodeURIComponent(v)}
function openUrl(raw){const url=normalize(raw);if(!url)return;const t=activeTab();t.url=url;t.title=url.replace(/^https?:\/\//,"").split("/")[0];address.value=url;pageTitle.textContent=t.title;homePage.classList.add("hidden");browserPage.classList.remove("hidden");blocked.classList.add("hidden");webview.classList.remove("hidden");webview.src=url;history.unshift({url,title:t.title,time:new Date().toLocaleString("id-ID")});history=history.filter((x,i,a)=>i===a.findIndex(y=>y.url===x.url));save();renderHistory();renderTabs()}
function closeTab(id){if(tabs.length===1){tabs[0]={id:1,url:"",title:"Tab baru"};active=1}else{const i=tabs.findIndex(t=>t.id===id);tabs.splice(i,1);if(active===id)active=tabs[Math.max(0,i-1)].id}showTab()}
function newTab(){const id=Date.now();tabs.push({id,url:"",title:"Tab baru"});active=id;showTab()}
function renderHistory(){historyList.innerHTML=history.length?history.map((x,i)=>'<div class="history-item" data-i="'+i+'"><b>'+esc(x.title)+'</b><small>'+esc(x.url)+'</small><small>'+esc(x.time)+'</small></div>').join(""):'<p style="padding:18px;color:#8996a4">Belum ada riwayat.</p>';historyList.querySelectorAll(".history-item").forEach(e=>e.onclick=()=>{openUrl(history[+e.dataset.i].url);historyPanel.classList.add("hidden")})}
document.getElementById("navForm").onsubmit=e=>{e.preventDefault();openUrl(address.value)};document.getElementById("searchForm").onsubmit=e=>{e.preventDefault();openUrl(document.getElementById("searchInput").value)};document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>openUrl(b.dataset.url));
document.getElementById("newTab").onclick=newTab;document.getElementById("home").onclick=()=>{activeTab().url="";activeTab().title="Tab baru";showTab()};document.getElementById("reload").onclick=()=>{if(activeTab().url)webview.src=activeTab().url};document.getElementById("back").onclick=()=>{try{webview.contentWindow.history.back()}catch(e){}};document.getElementById("forward").onclick=()=>{try{webview.contentWindow.history.forward()}catch(e){}};
document.getElementById("menuBtn").onclick=()=>menu.classList.toggle("hidden");document.getElementById("copyUrl").onclick=async()=>{if(address.value)await navigator.clipboard?.writeText(address.value);menu.classList.add("hidden")};document.getElementById("desktopMode").onclick=()=>{desktop=!desktop;document.getElementById("desktopMode").textContent=desktop?"Mode mobile":"Mode desktop";webview.style.minWidth=desktop?"1200px":"0";menu.classList.add("hidden")};document.getElementById("historyBtn").onclick=()=>{renderHistory();historyPanel.classList.remove("hidden");menu.classList.add("hidden")};document.getElementById("closeHistory").onclick=()=>historyPanel.classList.add("hidden");document.getElementById("clearHistory").onclick=()=>{history=[];save();renderHistory();menu.classList.add("hidden")};document.getElementById("homeMenu").onclick=()=>{document.getElementById("home").click();menu.classList.add("hidden")};document.getElementById("openDirect").onclick=()=>window.open(activeTab().url,"_blank");document.getElementById("blockedOpen").onclick=()=>window.open(activeTab().url,"_blank");
webview.addEventListener("load",()=>{blocked.classList.add("hidden");webview.classList.remove("hidden")});setTimeout(()=>{if(activeTab().url){blocked.classList.remove("hidden")}},5000);renderHistory();showTab();