const $=id=>document.getElementById(id),homePage=$("homePage"),browserPage=$("browserPage"),address=$("address"),pageTitle=$("pageTitle"),tabsEl=$("tabs"),menu=$("menu"),historyPanel=$("historyPanel"),historyList=$("historyList");let tabs=[{id:1,url:"",title:"Tab baru"}],active=1,desktop=false,deferredPrompt=null;const key="webbrowser-history";let history=JSON.parse(localStorage.getItem(key)||"[]");
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));const save=()=>localStorage.setItem(key,JSON.stringify(history.slice(0,100)));const activeTab=()=>tabs.find(t=>t.id===active);
function renderTabs(){tabsEl.innerHTML=tabs.map(t=>`<div class="tab ${t.id===active?"active":""}" data-id="${t.id}"><span class="tab-title">${esc(t.title)}</span><button class="tab-close" data-close="${t.id}">×</button></div>`).join("");tabsEl.querySelectorAll(".tab").forEach(e=>e.onclick=()=>{active=+e.dataset.id;showTab()});tabsEl.querySelectorAll("[data-close]").forEach(e=>e.onclick=x=>{x.stopPropagation();closeTab(+e.dataset.close)})}
function showTab(){const t=activeTab();address.value=t.url||"";pageTitle.textContent=t.title;renderTabs();if(t.url){homePage.classList.add("hidden");browserPage.classList.remove("hidden")}else{browserPage.classList.add("hidden");homePage.classList.remove("hidden")}}
function normalize(v){v=v.trim();if(!v)return"";if(/^https?:\/\//i.test(v))return v;if(v.includes(".")&&!v.includes(" "))return"https://"+v;return"https://www.google.com/search?q="+encodeURIComponent(v)}
function openUrl(raw){const url=normalize(raw);if(!url)return;const t=activeTab();t.url=url;t.title=url.replace(/^https?:\/\//,"").split("/")[0];address.value=url;pageTitle.textContent=t.title;homePage.classList.add("hidden");browserPage.classList.remove("hidden");openDirect(url);history.unshift({url,title:t.title,time:new Date().toLocaleString("id-ID")});history=history.filter((x,i,a)=>i===a.findIndex(y=>y.url===x.url));save();renderHistory();renderTabs()}
function closeTab(id){if(tabs.length===1){tabs[0]={id:1,url:"",title:"Tab baru"};active=1}else{const i=tabs.findIndex(t=>t.id===id);tabs.splice(i,1);if(active===id)active=tabs[Math.max(0,i-1)].id}showTab()}function newTab(){const id=Date.now();tabs.push({id,url:"",title:"Tab baru"});active=id;showTab()}
function renderHistory(){historyList.innerHTML=history.length?history.map((x,i)=>`<div class="history-item" data-i="${i}"><b>${esc(x.title)}</b><small>${esc(x.url)}</small><small>${esc(x.time)}</small></div>`).join(""):'<p style="padding:18px;color:#8996a4">Belum ada riwayat.</p>';historyList.querySelectorAll(".history-item").forEach(e=>e.onclick=()=>{openUrl(history[+e.dataset.i].url);historyPanel.classList.add("hidden")})}
$("navForm").onsubmit=e=>{e.preventDefault();openUrl(address.value)};$("searchForm").onsubmit=e=>{e.preventDefault();openUrl($("searchInput").value)};document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>openUrl(b.dataset.url));
$("newTab").onclick=newTab;$("home").onclick=()=>{activeTab().url="";activeTab().title="Tab baru";showTab()};$("reload").onclick=()=>{if(activeTab().url)openDirect(activeTab().url)};$("back").onclick=()=>history.back();$("forward").onclick=()=>history.forward();
$("menuBtn").onclick=()=>menu.classList.toggle("hidden");$("copyUrl").onclick=async()=>{if(address.value)await navigator.clipboard?.writeText(address.value);menu.classList.add("hidden")};$("desktopMode").onclick=()=>{desktop=!desktop;$("desktopMode").textContent=desktop?"Mode mobile":"Mode desktop";menu.classList.add("hidden")};$("historyBtn").onclick=()=>{renderHistory();historyPanel.classList.remove("hidden");menu.classList.add("hidden")};$("closeHistory").onclick=()=>historyPanel.classList.add("hidden");$("clearHistory").onclick=()=>{history=[];save();renderHistory();menu.classList.add("hidden")};$("homeMenu").onclick=()=>{$("home").click();menu.classList.add("hidden")};function openDirect(url){if(!url)return;window.open(url,"_blank","noopener,noreferrer")}
$("openDirect").onclick=()=>openDirect(activeTab().url);$("blockedOpen").onclick=()=>openDirect(activeTab().url);
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").classList.add("hidden");menu.classList.add("hidden")};if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
renderHistory();showTab();