const $=id=>document.getElementById(id);let current=null;let settings={crop:"center",tolerance:88};
async function load(){const s=await chrome.storage.local.get(["patterns","settings"]);settings={...settings,...(s.settings||{})};$("crop").value=settings.crop;$("tolerance").value=settings.tolerance;$("tolValue").textContent=settings.tolerance+"%";render(s.patterns||[])}
async function capture(){const r=await chrome.runtime.sendMessage({type:"CAPTURE",crop:settings.crop});if(r?.error)throw new Error(r.error);return r}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[c]))}
function render(ps){$("count").textContent=ps.length;$("list").innerHTML=ps.map((p,i)=>'<div class="item"><strong>#'+(i+1)+' — '+esc(p.title)+'</strong><span>'+new Date(p.createdAt).toLocaleString()+' • '+p.score+' zona</span></div>').join("")||'<div class="item">Belum ada pola.</div>'}
async function saveSettings(){settings.crop=$("crop").value;settings.tolerance=Number($("tolerance").value);await chrome.storage.local.set({settings})}
$("crop").onchange=saveSettings;$("tolerance").oninput=()=>{$("tolValue").textContent=$("tolerance").value+"%";saveSettings()};
$("record").onclick=async()=>{try{await saveSettings();current=await capture();$("status").textContent="Pola direkam: "+current.score+" zona. Tekan SIMPAN POLA."}catch(e){$("status").textContent="Gagal: "+e.message}};
$("save").onclick=async()=>{if(!current){$("status").textContent="Tekan RECORD POLA dulu.";return}const d=await chrome.storage.local.get("patterns"),ps=d.patterns||[];ps.push({...current,createdAt:Date.now()});await chrome.storage.local.set({patterns:ps});current=null;render(ps);$("status").textContent="Pola tersimpan."};
$("check").onclick=async()=>{try{await saveSettings();const d=await chrome.storage.local.get("patterns"),ps=d.patterns||[];if(!ps.length){$("status").textContent="Belum ada pola.";return}const now=await capture();let best=-1,bestScore=0;for(let i=0;i<ps.length;i++){const s=zoneSimilarity(now.zones,ps[i].zones);if(s>bestScore){bestScore=s;best=i}}$("match").textContent=Math.round(bestScore*100)+"%";if(best>=0&&bestScore>=settings.tolerance/100){$("status").textContent="🟢 POLA DITEMUKAN — #"+(best+1);await chrome.runtime.sendMessage({type:"NOTIFY",title:"Pola Solitaire ditemukan",message:"Cocok dengan pola #"+(best+1)+" ("+Math.round(bestScore*100)+"%)."})}else $("status").textContent="⚪ Tidak ada pola yang memenuhi toleransi."}catch(e){$("status").textContent="Gagal: "+e.message}};
function zoneSimilarity(a,b){if(!a||!b||a.length!==b.length)return 0;let total=0;for(let i=0;i<a.length;i++)total+=bitSimilarity(a[i],b[i]);return total/a.length}
function bitSimilarity(a,b){let same=0;for(let i=0;i<a.length;i++)if(a[i]===b[i])same++;return same/a.length}
$("clear").onclick=async()=>{if(!confirm("Hapus semua pola?"))return;await chrome.storage.local.remove("patterns");render([]);$("status").textContent="Semua pola dihapus."};load();