const $=id=>document.getElementById(id);let current=null;let settings={crop:"center",tolerance:90};
async function load(){const s=await chrome.storage.local.get(["patterns","settings"]);settings={...settings,...(s.settings||{})};$("crop").value=settings.crop;$("tolerance").value=settings.tolerance;$("tolValue").textContent=settings.tolerance+"%";render(s.patterns||[])}
async function capture(){const r=await chrome.runtime.sendMessage({type:"CAPTURE",crop:settings.crop});if(r?.error)throw new Error(r.error);return r}
function render(patterns){$("count").textContent=patterns.length;$("list").innerHTML=patterns.map((p,i)=>'<div class="item"><strong>#'+(i+1)+' — '+escapeHtml(p.title)+'</strong><span>'+new Date(p.createdAt).toLocaleString()+' • '+p.hash+'</span></div>').join("")||'<div class="item">Belum ada pola.</div>'}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[c]))}
function similarity(a,b){if(!a||!b||a.length!==b.length)return 0;let same=0;for(let i=0;i<a.length;i++)if(a[i]===b[i])same++;return same/a.length}
async function saveSettings(){settings.crop=$("crop").value;settings.tolerance=Number($("tolerance").value);await chrome.storage.local.set({settings})}
$("crop").onchange=saveSettings;$("tolerance").oninput=()=>{$("tolValue").textContent=$("tolerance").value+"%";saveSettings()};
$("record").onclick=async()=>{try{await saveSettings();current=await capture();$("status").textContent="Pola direkam. Tekan SIMPAN POLA."}catch(e){$("status").textContent="Gagal: "+e.message}};
$("save").onclick=async()=>{if(!current){$("status").textContent="Tekan RECORD POLA dulu.";return}const data=await chrome.storage.local.get("patterns");const patterns=data.patterns||[];patterns.push({...current,createdAt:Date.now()});await chrome.storage.local.set({patterns});current=null;render(patterns);$("status").textContent="Pola berhasil disimpan."};
$("check").onclick=async()=>{try{await saveSettings();const data=await chrome.storage.local.get("patterns");const patterns=data.patterns||[];if(!patterns.length){$("status").textContent="Belum ada pola tersimpan.";return}const now=await capture();let best=-1,bestScore=0;for(let i=0;i<patterns.length;i++){const score=similarity(now.hash,patterns[i].hash);if(score>bestScore){bestScore=score;best=i}}$("match").textContent=best>=0?Math.round(bestScore*100)+"%":"-";if(best>=0&&bestScore>=settings.tolerance/100){$("status").textContent="🟢 POLA PERMAINAN DITEMUKAN — #"+(best+1);await chrome.runtime.sendMessage({type:"NOTIFY",title:"Pola permainan ditemukan",message:"Posisi sekarang cocok dengan pola #"+(best+1)+" ("+Math.round(bestScore*100)+"%)."})}else{$("status").textContent="⚪ Belum ada pola yang cocok."}}catch(e){$("status").textContent="Gagal: "+e.message}};
$("clear").onclick=async()=>{if(!confirm("Hapus semua pola?"))return;await chrome.storage.local.remove("patterns");render([]);$("status").textContent="Semua pola dihapus."};load();