const DEF={threshold:.965,delay:120,crop:{left:.05,top:.08,width:.9,height:.84}},tabs=new Map(),pending=new Map(),replays=new Map();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
async function settings(){const {v5settings={}}=await chrome.storage.local.get("v5settings");return {...DEF,...v5settings}}
async function records(){return (await chrome.storage.local.get("v5records")).v5records||[]}async function save(a){await chrome.storage.local.set({v5records:a})}
async function capture(tabId){const tab=await chrome.tabs.get(tabId),url=await chrome.tabs.captureVisibleTab(tab.windowId,{format:"png"}),res=await fetch(url),bmp=await createImageBitmap(await res.blob()),c=DEF.crop,sx=bmp.width*c.left,sy=bmp.height*c.top,sw=bmp.width*c.width,sh=bmp.height*c.height,can=new OffscreenCanvas(sw,sh),ctx=can.getContext("2d",{willReadFrequently:true});ctx.drawImage(bmp,sx,sy,sw,sh,0,0,sw,sh);const im=ctx.getImageData(0,0,sw,sh),small=new Uint8Array(48*48);let sum=0;for(let y=0;y<48;y++)for(let x=0;x<48;x++){const i=(Math.floor(y*sh/48)*sw+Math.floor(x*sw/48))*4,g=.299*im.data[i]+.587*im.data[i+1]+.114*im.data[i+2];small[y*48+x]=g;sum+=g}const mean=sum/small.length;let bits="";for(const v of small)bits+=v>=mean?"1":"0";return{bits,mean,viewport:{width:tab.width||0,height:tab.height||0},url:tab.url}}
const sim=(a,b)=>{if(!a||!b||a.bits.length!==b.bits.length)return 0;let d=0;for(let i=0;i<a.bits.length;i++)if(a.bits[i]!==b.bits[i])d++;return 1-d/a.bits.length};
async function match(deal){const rs=await records(),s=await settings();let best=null;for(const r of rs){const score=sim(deal,r.deal);if(!best||score>best.score)best={r,score}}return best&&best.score>=s.threshold?best:null}
async function notifyMatch(tabId,m){const id="match-"+tabId+"-"+Date.now();pending.set(id,{tabId,recordingId:m.r.id});await chrome.notifications.create(id,{type:"basic",iconUrl:"v5/icon.svg",title:"🟢 POLA PERMAINAN DITEMUKAN",message:m.r.name+" • "+m.r.actions.length+" langkah • "+(m.score*100).toFixed(1)+"% cocok",requireInteraction:true,buttons:[{title:"▶ JALANKAN"},{title:"TUTUP"}]})}
async function begin(tabId){const st={recording:true,actions:[],initial:null,match:null};tabs.set(tabId,st);await sleep(800);try{st.initial=await capture(tabId);const m=await match(st.initial);if(m){st.match={id:m.r.id,score:m.score};await notifyMatch(tabId,m)}}catch(e){console.warn("V5 capture",e)}}
async function finish(tabId){const st=tabs.get(tabId);if(!st?.initial||!st.actions.length)return;const rs=await records();rs.unshift({id:crypto.randomUUID(),name:"Game "+new Date().toLocaleString(),createdAt:new Date().toISOString(),deal:st.initial,actions:st.actions});await save(rs.slice(0,200));st.recording=false;tabs.set(tabId,st);await chrome.notifications.create("saved-"+Date.now(),{type:"basic",iconUrl:"v5/icon.svg",title:"✓ Permainan direkam",message:st.actions.length+" langkah tersimpan"})}
async function input(tabId,m,p){return chrome.debugger.sendCommand({tabId},m,p)}
async function replay(tabId,id){if(replays.has(tabId))return;const r=(await records()).find(x=>x.id===id);if(!r)return;const q={stop:false,i:0};replays.set(tabId,q);try{await chrome.debugger.attach({tabId},"1.3");await input(tabId,"Runtime.evaluate",{expression:"window.scrollTo(0,0)"});await chrome.notifications.create("replay-"+tabId,{type:"basic",iconUrl:"v5/icon.svg",title:"▶ Replay berjalan",message:"Langkah 0 / "+r.actions.length,buttons:[{title:"STOP"}]});for(let i=0;i<r.actions.length&&!q.stop;i++){q.i=i+1;const a=r.actions[i];await sleep(clamp(a.wait||0,40,5000));if(a.kind==="drag"){await input(tabId,"Input.dispatchMouseEvent",{type:"mousePressed",x:a.x1,y:a.y1,button:"left",clickCount:1});await sleep(clamp(a.duration||100,20,1000));await input(tabId,"Input.dispatchMouseEvent",{type:"mouseMoved",x:a.x2,y:a.y2,button:"left",buttons:1});await input(tabId,"Input.dispatchMouseEvent",{type:"mouseReleased",x:a.x2,y:a.y2,button:"left",clickCount:1})}else{await input(tabId,"Input.dispatchMouseEvent",{type:"mousePressed",x:a.x1,y:a.y1,button:"left",clickCount:1});await sleep(clamp(a.duration||70,20,600));await input(tabId,"Input.dispatchMouseEvent",{type:"mouseReleased",x:a.x1,y:a.y1,button:"left",clickCount:1})}await chrome.notifications.update("replay-"+tabId,{type:"basic",iconUrl:"v5/icon.svg",title:"▶ Replay berjalan",message:"Langkah "+(i+1)+" / "+r.actions.length,buttons:[{title:"STOP"}]});await sleep((await settings()).delay)}}catch(e){await chrome.notifications.create("replay-error-"+Date.now(),{type:"basic",iconUrl:"v5/icon.svg",title:"Replay gagal",message:String(e.message||e)})}finally{replays.delete(tabId);try{await chrome.debugger.detach({tabId})}catch(e){}}}
chrome.notifications.onButtonClicked.addListener(async(id,i)=>{const p=pending.get(id);if(p){pending.delete(id);if(i===0)await replay(p.tabId,p.recordingId);return}for(const [tab,q] of replays)if(id==="replay-"+tab&&i===0)q.stop=true});
chrome.runtime.onMessage.addListener((m,s,reply)=>{(async()=>{const tabId=s.tab?.id;if(!tabId){const ts=await chrome.tabs.query({active:true,currentWindow:true}),id=ts[0]?.id;if(m.type==="POPUP_GET_STATE"){const q=tabs.get(id);return{ok:true,state:q?{recording:q.recording,actionCount:q.actions.length,match:q.match}:null}}if(m.type==="POPUP_LIST")return{ok:true,recordings:await records()};if(m.type==="POPUP_START"){tabs.set(id,{recording:true,actions:[],initial:await capture(id),match:null});return{ok:true}}if(m.type==="POPUP_FINISH"){await finish(id);return{ok:true}}if(m.type==="POPUP_REPLAY"){await replay(id,m.recordingId);return{ok:true}}if(m.type==="POPUP_STOP_REPLAY"){const q=replays.get(id);if(q)q.stop=true;return{ok:true}}if(m.type==="POPUP_DELETE"){await save((await records()).filter(x=>x.id!==m.recordingId));return{ok:true}}throw Error("Pesan tidak dikenal")}const st=tabs.get(tabId)||{recording:false,actions:[]};if(m.type==="PAGE_READY"){await begin(tabId);return{ok:true}}if(m.type==="NEW_GAME_REQUESTED"){await finish(tabId);await begin(tabId);return{ok:true}}if(m.type==="GAME_ACTION"){if(st.recording&&!replays.has(tabId))st.actions.push(m.action);tabs.set(tabId,st);return{ok:true}}if(m.type==="GAME_FINISHED"){await finish(tabId);return{ok:true}}})().then(reply).catch(e=>reply({ok:false,error:String(e.message||e)}));return true});
chrome.tabs.onRemoved.addListener(id=>{tabs.delete(id);replays.delete(id)})